# This is a basic workflow to help you get started with Actions

name: DEPLOY TO TESTING

on: 
  push:
    branches:
      - testing

jobs:
  build:

    runs-on: ubuntu-latest
    environment: main
    steps:
    - uses: actions/checkout@v3

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "."
        target: "/var/www/parking-winds-stable/"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: ls
